
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-12-01 using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=createImageEdit_2ea6863d9a
ROOST_METHOD_SIG_HASH=createImageEdit_bcb5839b0d

Here are your existing test cases which we found out and are not considered for test generation:

File Path: C:\var\tmp\Roost\RoostGPT\Java-12-01\1768213766\source\openai-java\service\src\test\java\com\theokanning\openai\service\ImageTest.java
Tests:
    "@Test
void createImageEdit() {
        CreateImageEditRequest createImageRequest = CreateImageEditRequest.builder().prompt("a penguin with a red background").responseFormat("url").size("256x256").user("testing").n(2).build();
        List<Image> images = service.createImageEdit(createImageRequest, fileWithAlphaPath, null).getData();
        assertEquals(2, images.size());
        assertNotNull(images.get(0).getUrl());
    }
"
    "@Test
void createImageEditWithMask() {
        CreateImageEditRequest createImageRequest = CreateImageEditRequest.builder().prompt("a penguin with a red hat").responseFormat("url").size("256x256").user("testing").n(2).build();
        List<Image> images = service.createImageEdit(createImageRequest, filePath, maskPath).getData();
        assertEquals(2, images.size());
        assertNotNull(images.get(0).getUrl());
    }
"Scenario 1: Create image edit with all valid parameters including mask and model

Details:  
  TestName: createImageEditWithMaskAndModel
  Description: This scenario is designed to verify that createImageEdit correctly handles a request that provides all valid parameters: a prompt, size, response format, n value, user string, mask image, and model name. It checks if the service processes the multipart request as expected when both image and mask files are present, and the model is specified.

Execution:
  Arrange: Prepare a CreateImageEditRequest with all values (prompt, size, responseFormat, user, n, model), and create java.io.File objects for image and mask.
  Act: Call createImageEdit(request, image, mask) on the OpenAiService.
  Assert: Use assertions to check that the returned ImageResult contains expected data (e.g., list of images, correct size of images, url or base64 string format).
Validation: 
  This assertion verifies that the API can process all input fields correctly and return the corresponding image edit results. It confirms that optional parameters such as mask and model are incorporated in the request as intended.

Scenario 2: Create image edit with minimum required fields (only image, no mask)

Details:  
  TestName: createImageEditWithMinimumFields
  Description: This scenario checks the behavior of createImageEdit when only the required fields are provided. The request does not include a mask or model, ensuring the method works for basic image edit functionality.

Execution:
  Arrange: Construct CreateImageEditRequest with basic prompt, size, and responseFormat (no mask, no model, no n). Create an image java.io.File.
  Act: Call createImageEdit(request, image, null) on OpenAiService.
  Assert: Assert that the ImageResult exists and contains valid data (such as one or more generated images).
Validation: 
  The assertion verifies that the method can successfully process a minimal input, delivering a valid ImageResult with only an image provided, confirming basic service reliability.

Scenario 3: Create image edit with null image file

Details:  
  TestName: createImageEditWithNullImage
  Description: This scenario validates that createImageEdit robustly handles the case where the main image file argument is null, which is an invalid operation.

Execution:
  Arrange: Build a valid CreateImageEditRequest. Set image argument to null.
  Act: Invoke createImageEdit(request, null, null) on OpenAiService.
  Assert: Assert that the method throws an appropriate exception (such as NullPointerException or a custom API error).
Validation: 
  The assertion ensures that the service enforces required parameters (image must not be null), thereby maintaining data integrity and preventing unintended errors during upload.

Scenario 4: Create image edit with invalid mask file (file does not exist)

Details:  
  TestName: createImageEditWithInvalidMaskFile
  Description: Verifies that createImageEdit gracefully handles scenarios where the provided mask file is invalid (e.g., file is missing or corrupted).

Execution:
  Arrange: Prepare a valid CreateImageEditRequest and an image java.io.File. For the mask, reference a file path that does not exist to create a java.io.File instance.
  Act: Call createImageEdit(request, image, mask) where mask file does not exist.
  Assert: Check that the method raises an exception or returns an error response (e.g., OpenAiHttpException).
Validation: 
  This test checks the robustness of file processing logic for mask files, ensuring that the method can detect and handle missing or invalid files, improving overall error handling.

Scenario 5: Create image edit with null request object

Details:  
  TestName: createImageEditWithNullRequest
  Description: This test checks the system’s integrity when the CreateImageEditRequest argument is null, validating that the service does not execute incomplete or invalid requests.

Execution:
  Arrange: Set request argument to null, create valid image and mask java.io.File if needed.
  Act: Call createImageEdit(null, image, mask).
  Assert: Assert that an appropriate exception is thrown (such as NullPointerException or an API error).
Validation: 
  The assertion enforces that the API requires non-null request objects and protects against null pointer or malformed request issues.

Scenario 6: Create image edit with invalid image file (file does not exist)

Details:  
  TestName: createImageEditWithInvalidImageFile
  Description: Verifies how createImageEdit behaves when the primary image file is invalid (e.g., references a non-existent file).

Execution:
  Arrange: Construct a valid CreateImageEditRequest and use an image java.io.File with a non-existent path.
  Act: Call createImageEdit(request, image, null).
  Assert: Assert for thrown exception or error response due to missing image file.
Validation: 
  The assertion checks for correct error signaling from the API when input file prerequisites are not met.

Scenario 7: Create image edit with null fields in request (e.g., prompt, size, responseFormat)

Details:  
  TestName: createImageEditWithNullFieldsInRequest
  Description: This scenario checks how the method handles a request where critical fields like prompt, size, or responseFormat are null.

Execution:
  Arrange: Prepare a CreateImageEditRequest object with null values for prompt, size, and responseFormat. Provide a valid image java.io.File.
  Act: Call createImageEdit(request, image, null).
  Assert: Assert that the method throws an exception or returns an error indicating invalid request structure.
Validation: 
  Ensures that the API’s required fields are strictly checked, maintaining necessary contract enforcement with OpenAI’s backend.

Scenario 8: Create image edit with very large n value

Details:  
  TestName: createImageEditWithLargeNValue
  Description: Checks if createImageEdit can handle unusually large values for n (number of images requested), and how the system behaves—whether it returns a capped list, error, or supports the request.

Execution:
  Arrange: Build a CreateImageEditRequest with a very high n (e.g., 1000), valid prompt, size, and responseFormat. Use valid image file.
  Act: Call createImageEdit(request, image, null).
  Assert: Assert that the ImageResult is either as expected (capped, error, or successful list), depending on the API’s documented limitation.
Validation: 
  Validates that service logic enforces or handles upper-bound limits for generated images as per API design, shielding the server and client from resource misuse.

Scenario 9: Create image edit with unsupported response format

Details:  
  TestName: createImageEditWithUnsupportedResponseFormat
  Description: Challenges the method’s handling of an unsupported or unknown responseFormat value (e.g., something not recognized by OpenAI’s API).

Execution:
  Arrange: Prepare CreateImageEditRequest with valid fields but an unsupported responseFormat (e.g., "txt"), valid image file.
  Act: Call createImageEdit(request, image, null).
  Assert: Assert that the method throws an API error or returns a meaningful error response.
Validation: 
  This test helps validate the mapping of request parameters to backend requirements, ensuring graceful handling of unsupported options and clearer feedback.

Scenario 10: Create image edit with unsupported image file type

Details:  
  TestName: createImageEditWithUnsupportedImageFileType
  Description: Evaluates the behavior when the provided image file is of a type that is not accepted (e.g., a text file instead of a png or jpg).

Execution:
  Arrange: Prepare CreateImageEditRequest with all valid fields; set image file to an unsupported extension/type (e.g., “image.txt”).
  Act: Call createImageEdit(request, image, null).
  Assert: Assert that the method throws an exception or returns an error indicating unsupported file format.
Validation: 
  Ensures that input validation for file type is enforced and that meaningful errors are produced for invalid file uploads, safeguarding the API usage requirements.

Scenario 11: Create image edit when API client throws HttpException with parseable error body

Details:  
  TestName: createImageEditWithHttpExceptionAndParseableError
  Description: Tests how createImageEdit behaves when the service throws an HttpException containing a parseable error response body. Verifies that the OpenAiHttpException is properly raised.

Execution:
  Arrange: Mock the api.createImageEdit call to throw HttpException with a valid errorBody representing an OpenAiError.
  Act: Invoke createImageEdit(request, image, mask).
  Assert: Assert that OpenAiHttpException is thrown with correct error code and message.
Validation: 
  Validates exception handling and error propagation, ensuring API errors are interpreted and exposed to the user appropriately.

Scenario 12: Create image edit when API client throws HttpException with null or non-parseable error body

Details:  
  TestName: createImageEditWithHttpExceptionAndUnparseableError
  Description: Evaluates system behavior when HttpException occurs during the API call, but the error body is either null or cannot be parsed (e.g., corrupted or unexpected format).

Execution:
  Arrange: Mock api.createImageEdit call to throw HttpException with null or non-parseable errorBody.
  Act: Call createImageEdit(request, image, mask).
  Assert: Assert that the original HttpException is propagated or handled appropriately.
Validation: 
  This assertion ensures resilience and correct exception forwarding even when error information cannot be deserialized, maintaining transparency in error management.

Scenario 13: Create image edit using a request specifying an unknown model

Details:  
  TestName: createImageEditWithUnknownModel
  Description: Tests if the service correctly processes or returns an error for requests where the model parameter is set to a string not recognized by the backend.

Execution:
  Arrange: Create a CreateImageEditRequest with model set to an unknown/nonexistent model name, and valid image file.
  Act: Call createImageEdit(request, image, null).
  Assert: Assert that the error response or exception communicates that the model cannot be found or used.
Validation: 
  Confirms that model validation occurs at the backend and that the service exposes meaningful errors for unsupported model choices, helping client developers debug issues quickly.

Scenario 14: Create image edit with image as a zero-byte file

Details:  
  TestName: createImageEditWithZeroByteImageFile
  Description: Checks system’s capability to handle an image file that is present but contains zero bytes.

Execution:
  Arrange: Prepare valid CreateImageEditRequest, set the image java.io.File to a zero-byte file.
  Act: Invoke createImageEdit(request, image, null).
  Assert: Assert the occurrence of an error or failure, as image content is required for edits.
Validation: 
  Maintains input file content validation and ensures that backend will not accept empty uploads, enforcing proper input checks.

Scenario 15: Create image edit with mask as a zero-byte file

Details:  
  TestName: createImageEditWithZeroByteMaskFile
  Description: Tests service response when mask file is present but has zero bytes (empty file).

Execution:
  Arrange: Prepare CreateImageEditRequest and provide valid image file, mask java.io.File points to zero-byte file.
  Act: Call createImageEdit(request, image, mask).
  Assert: Assert error response due to invalid mask content.
Validation: 
  Important to verify that every aspect of the multipart request is validated, avoiding the inclusion of empty masks with potential malfunctions.

Scenario 16: Create image edit with negative n value

Details:  
  TestName: createImageEditWithNegativeNValue
  Description: Validates system behavior when the request specifies a negative n (number of images), which should be rejected.

Execution:
  Arrange: Build CreateImageEditRequest with n set to a negative value, otherwise valid fields.
  Act: Invoke createImageEdit(request, image, null).
  Assert: Assert that an error or exception is thrown (parameter out of range).
Validation: 
  Ensures correct enforcement of parameter domains, preventing nonsensical or erroneous input from being accepted by the API.

Scenario 17: Create image edit with all optional fields absent

Details:  
  TestName: createImageEditWithOnlyMandatoryFields
  Description: Checks if the service can perform an edit with only prompt, size, and responseFormat—leaving n, mask, user, and model as null.

Execution:
  Arrange: Create CreateImageEditRequest with only prompt, size, and responseFormat, and a valid image file.
  Act: Call createImageEdit(request, image, null).
  Assert: Assert that ImageResult contains default or single image.
Validation: 
  Verifies default handlings, such as number of images and model assignment when options are left out, ensuring fallback logic works.

Scenario 18: Create image edit when executorService is null

Details:  
  TestName: createImageEditWithNullExecutorService
  Description: Checks if the absence of a configured ExecutorService in OpenAiService influences the createImageEdit execution path.

Execution:
  Arrange: Create OpenAiService with only api instance, not specifying executorService. Construct valid request and image.
  Act: Call createImageEdit(request, image, null).
  Assert: Assert that request is processed or error is thrown only if executor is required.
Validation: 
  Ensures service can gracefully run without an executorService or properly communicate setup issues to the user.

*/

// ********RoostGPT********
package com.theokanning.openai.service;import com.theokanning.openai.OpenAiApi;
import com.theokanning.openai.OpenAiHttpException;
import com.theokanning.openai.OpenAiError;
import com.theokanning.openai.image.CreateImageEditRequest;
import com.theokanning.openai.image.ImageResult;
import io.reactivex.Single;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;
import okhttp3.ResponseBody;
import okhttp3.MediaType;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import retrofit2.HttpException;
import java.io.File;
import java.io.IOException;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.node.TextNode;
import com.theokanning.openai.*;
import com.theokanning.openai.assistants.*;
import com.theokanning.openai.audio.*;
import com.theokanning.openai.billing.BillingUsage;
import com.theokanning.openai.billing.Subscription;
import com.theokanning.openai.client.OpenAiApi;
import com.theokanning.openai.completion.CompletionChunk;
import com.theokanning.openai.completion.CompletionRequest;
import com.theokanning.openai.completion.CompletionResult;
import com.theokanning.openai.completion.chat.*;
import com.theokanning.openai.edit.EditRequest;
import com.theokanning.openai.edit.EditResult;
import com.theokanning.openai.embedding.EmbeddingRequest;
import com.theokanning.openai.embedding.EmbeddingResult;
import com.theokanning.openai.file.File;
import com.theokanning.openai.fine_tuning.FineTuningEvent;
import com.theokanning.openai.fine_tuning.FineTuningJob;
import com.theokanning.openai.fine_tuning.FineTuningJobRequest;
import com.theokanning.openai.finetune.FineTuneEvent;
import com.theokanning.openai.finetune.FineTuneRequest;
import com.theokanning.openai.finetune.FineTuneResult;
import com.theokanning.openai.image.CreateImageRequest;
import com.theokanning.openai.image.CreateImageVariationRequest;
import com.theokanning.openai.messages.Message;
import com.theokanning.openai.messages.MessageFile;
import com.theokanning.openai.messages.MessageRequest;
import com.theokanning.openai.messages.ModifyMessageRequest;
import com.theokanning.openai.model.Model;
import com.theokanning.openai.moderation.ModerationRequest;
import com.theokanning.openai.moderation.ModerationResult;
import com.theokanning.openai.runs.CreateThreadAndRunRequest;
import com.theokanning.openai.runs.Run;
import com.theokanning.openai.runs.RunCreateRequest;
import com.theokanning.openai.runs.RunStep;
import com.theokanning.openai.runs.SubmitToolOutputsRequest;
import com.theokanning.openai.threads.Thread;
import com.theokanning.openai.threads.ThreadRequest;
import io.reactivex.BackpressureStrategy;
import io.reactivex.Flowable;
import okhttp3.*;
import retrofit2.Call;
import retrofit2.Retrofit;
import retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory;
import retrofit2.converter.jackson.JacksonConverterFactory;
import javax.validation.constraints.NotNull;
import java.time.Duration;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;

@ExtendWith(MockitoExtension.class)
class OpenAiServiceCreateImageEdit521Test {
    @Mock
    OpenAiApi api;
    @Mock
    Single<ImageResult> imageEditSingle;
    @InjectMocks
    OpenAiService service;
    CreateImageEditRequest makeRequest(String prompt, String size, String format, String user, Integer n, String model) {
        CreateImageEditRequest req = new CreateImageEditRequest();
        req.setPrompt(prompt);
        req.setSize(size);
        req.setResponseFormat(format);
        req.setUser(user);
        req.setN(n);
        req.setModel(model);
        return req;
    }
    java.io.File createTempFile(String suffix, int size) throws IOException {
        java.io.File tempFile = java.io.File.createTempFile("testImage", suffix);
        tempFile.deleteOnExit();
        if (size > 0) {
            byte[] content = new byte[size];
            java.nio.file.Files.write(tempFile.toPath(), content);
        }
        return tempFile;
    }
    @Test
    @Tag("valid")
    void testCreateImageEditWithMaskAndModel() throws IOException {
        CreateImageEditRequest request = makeRequest("edit-prompt", "1024x1024", "url", "userId", 2, "model-v1");
        java.io.File image = createTempFile(".png", 1024);
        java.io.File mask = createTempFile(".png", 512);
        ImageResult expected = new ImageResult();
        expected.setCreated(System.currentTimeMillis());
        expected.setData(java.util.Collections.singletonList(new ImageResult.Image("http://generated.image", null)));
        when(api.createImageEdit(any(MultipartBody.class))).thenReturn(Single.just(expected));
        OpenAiService svc = new OpenAiService(api);
        ImageResult actual = (ImageResult) svc.createImageEdit(request, image, mask);
        assertNotNull((Object) actual, "ImageResult should not be null");
        assertNotNull((Object) actual.getData(), "ImageResult data list should not be null");
        assertFalse(((List<ImageResult.Image>)actual.getData()).isEmpty(), "ImageResult data list should not be empty");
        assertTrue(((ImageResult.Image)((List<ImageResult.Image>)actual.getData()).get(0)).getUrl() != null ||
                   ((ImageResult.Image)((List<ImageResult.Image>)actual.getData()).get(0)).getB64Json() != null, "Each result should have url or b64Json");
        assertEquals(((List<ImageResult.Image>)expected.getData()).size(),
                     ((List<ImageResult.Image>)actual.getData()).size(), "Image count should match");
    }
    @Test
    @Tag("valid")
    void testCreateImageEditWithMinimumFields() throws IOException {
        CreateImageEditRequest request = makeRequest("edit-prompt", "512x512", "url", null, null, null);
        java.io.File image = createTempFile(".png", 1024);
        ImageResult expected = new ImageResult();
        expected.setCreated(System.currentTimeMillis());
        expected.setData(java.util.Collections.singletonList(new ImageResult.Image("http://image.url", null)));
        when(api.createImageEdit(any(MultipartBody.class))).thenReturn(Single.just(expected));
        OpenAiService svc = new OpenAiService(api);
        ImageResult actual = (ImageResult) svc.createImageEdit(request, image, null);
        assertNotNull((Object) actual, "ImageResult should not be null");
        assertNotNull((Object) actual.getData(), "ImageResult should contain data");
        assertFalse(((List<ImageResult.Image>)actual.getData()).isEmpty(), "Data should not be empty");
        assertTrue(((ImageResult.Image)((List<ImageResult.Image>)actual.getData()).get(0)).getUrl() != null ||
                   ((ImageResult.Image)((List<ImageResult.Image>)actual.getData()).get(0)).getB64Json() != null, "Should have a valid url/b64Json");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithNullImage() {
        CreateImageEditRequest request = makeRequest("prompt", "512x512", "url", null, 1, null);
        OpenAiService svc = new OpenAiService(api);
        assertThrows(NullPointerException.class, () -> svc.createImageEdit(request, null, null), "Should throw NullPointerException for null image");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithInvalidMaskFile() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "512x512", "url", null, null, null);
        java.io.File image = createTempFile(".png", 64);
        java.io.File mask = new java.io.File("/path/that/does/not/exist.png");  // File does not exist
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IOException("File not found")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IOException.class, () -> svc.createImageEdit(request, image, mask), "Should throw IOException for invalid mask file");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithNullRequest() throws IOException {
        java.io.File image = createTempFile(".png", 128);
        java.io.File mask = createTempFile(".png", 128);
        OpenAiService svc = new OpenAiService(api);
        assertThrows(NullPointerException.class, () -> svc.createImageEdit(null, image, mask), "Should throw NullPointerException for null request");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithInvalidImageFile() {
        CreateImageEditRequest request = makeRequest("prompt", "128x128", "url", null, null, null);
        java.io.File image = new java.io.File("/invalid/path/nonexistent.png"); // Non-existent file
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IOException("Image file not found")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IOException.class, () -> svc.createImageEdit(request, image, null), "Should throw IOException for invalid image file");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithNullFieldsInRequest() throws IOException {
        CreateImageEditRequest request = makeRequest(null, null, null, null, null, null);
        java.io.File image = createTempFile(".png", 100);
        OpenAiService svc = new OpenAiService(api);
        assertThrows(NullPointerException.class, () -> svc.createImageEdit(request, image, null), "Should throw NullPointerException for null fields in request");
    }
    @Test
    @Tag("boundary")
    void testCreateImageEditWithLargeNValue() throws IOException {
        int largeN = 1000;
        CreateImageEditRequest request = makeRequest("prompt", "256x256", "url", null, largeN, null);
        java.io.File image = createTempFile(".png", 512);
        ImageResult expected = new ImageResult();
        expected.setCreated(System.currentTimeMillis());
        java.util.List<ImageResult.Image> images = new java.util.ArrayList<>();
        for (int i = 0; i < 10; ++i) {
            images.add(new ImageResult.Image("http://image/" + i, null));
        }
        expected.setData(images);
        when(api.createImageEdit(any(MultipartBody.class))).thenReturn(Single.just(expected));
        OpenAiService svc = new OpenAiService(api);
        ImageResult actual = (ImageResult) svc.createImageEdit(request, image, null);
        assertNotNull((Object) actual);
        assertNotNull((Object) actual.getData());
        assertFalse(((List<ImageResult.Image>)actual.getData()).isEmpty());
        assertTrue(((List<ImageResult.Image>)actual.getData()).size() <= largeN, "Returned image count should not exceed requested n");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithUnsupportedResponseFormat() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "128x128", "txt", null, null, null);
        java.io.File image = createTempFile(".png", 200);
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IOException("Unsupported response format")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IOException.class, () -> svc.createImageEdit(request, image, null), "Should throw IOException for unsupported response format");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithUnsupportedImageFileType() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "128x128", "url", null, null, null);
        java.io.File image = createTempFile(".txt", 255); // Invalid extension
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IOException("Unsupported file type")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IOException.class, () -> svc.createImageEdit(request, image, null), "Should throw IOException for unsupported file type");
    }
    @Test
    @Tag("integration")
    void testCreateImageEditWithHttpExceptionAndParseableError() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "128x128", "url", null, null, null);
        java.io.File image = createTempFile(".png", 64);
        java.io.File mask = createTempFile(".png", 64);
        OpenAiError error = new OpenAiError();
        error.setMessage("API rate limit exceeded");
        error.setType("rate_limit");
        error.setParam(null);
        error.setCode("rate_limit");
        ResponseBody errorBody = ResponseBody.create(
                MediaType.get("application/json"),
                "{\"error\": {\"message\": \"API rate limit exceeded\", \"type\": \"rate_limit\", \"code\": \"rate_limit\"}}"
        );
        retrofit2.Response<ImageResult> response = retrofit2.Response.error(429, errorBody);
        HttpException httpException = new HttpException(response);
        when(api.createImageEdit(any(MultipartBody.class)))
                .thenReturn(Single.error(httpException));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(OpenAiHttpException.class, () -> svc.createImageEdit(request, image, mask), "Should throw OpenAiHttpException when API returns parseable error");
    }
    @Test
    @Tag("integration")
    void testCreateImageEditWithHttpExceptionAndUnparseableError() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "512x512", "url", null, null, null);
        java.io.File image = createTempFile(".png", 32);
        java.io.File mask = createTempFile(".png", 32);
        retrofit2.Response<ImageResult> response = retrofit2.Response.error(500, null); // errorBody null
        HttpException httpException = new HttpException(response);
        when(api.createImageEdit(any(MultipartBody.class)))
                .thenReturn(Single.error(httpException));
        OpenAiService svc = new OpenAiService(api);
        Exception ex = assertThrows(HttpException.class, () -> svc.createImageEdit(request, image, mask), "Should propagate HttpException if error body is null");
        assertEquals((Object) httpException, (Object) ex, "Exception must match original");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithUnknownModel() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "512x512", "url", null, null, "unknown-model");
        java.io.File image = createTempFile(".png", 128);
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IOException("The model 'unknown-model' does not exist")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IOException.class, () -> svc.createImageEdit(request, image, null), "Should throw IOException for unknown model");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithZeroByteImageFile() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "512x512", "url", null, null, null);
        java.io.File image = createTempFile(".png", 0);
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IOException("Image file is empty")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IOException.class, () -> svc.createImageEdit(request, image, null), "Should throw IOException for zero-byte image file");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithZeroByteMaskFile() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "512x512", "url", null, null, null);
        java.io.File image = createTempFile(".png", 128);
        java.io.File mask = createTempFile(".png", 0);
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IOException("Mask file is empty")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IOException.class, () -> svc.createImageEdit(request, image, mask), "Should throw IOException for zero-byte mask file");
    }
    @Test
    @Tag("invalid")
    void testCreateImageEditWithNegativeNValue() throws IOException {
        CreateImageEditRequest request = makeRequest("prompt", "512x512", "url", null, -5, null);
        java.io.File image = createTempFile(".png", 128);
        when(api.createImageEdit(any(MultipartBody.class)))
            .thenReturn(Single.error(new IllegalArgumentException("N must be non-negative")));
        OpenAiService svc = new OpenAiService(api);
        assertThrows(IllegalArgumentException.class, () -> svc.createImageEdit(request, image, null), "Should throw IllegalArgumentException for negative N");
    }
    @Test
    @Tag("valid")
    void testCreateImageEditWithOnlyMandatoryFields() throws IOException {
        CreateImageEditRequest request = makeRequest("edit-prompt", "256x256", "url", null, null, null);
        java.io.File image = createTempFile(".png", 256);
        ImageResult expected = new ImageResult();
        expected.setCreated(System.currentTimeMillis());
        expected.setData(java.util.Collections.singletonList(new ImageResult.Image("http://localhost/image.png", null)));
        when(api.createImageEdit(any(MultipartBody.class))).thenReturn(Single.just(expected));
        OpenAiService svc = new OpenAiService(api);
        ImageResult actual = (ImageResult) svc.createImageEdit(request, image, null);
        assertNotNull((Object) actual);
        assertNotNull((Object) actual.getData());
        assertEquals(1, ((List<ImageResult.Image>)actual.getData()).size(), "Should produce 1 image with default behavior");
        assertTrue(((ImageResult.Image)((List<ImageResult.Image>)actual.getData()).get(0)).getUrl() != null ||
            ((ImageResult.Image)((List<ImageResult.Image>)actual.getData()).get(0)).getB64Json() != null, "Image should have valid url/b64Json");
    }
    @Test
    @Tag("integration")
    void testCreateImageEditWithNullExecutorService() throws IOException {
        CreateImageEditRequest request = makeRequest("edit-prompt", "256x256", "url", null, null, null);
        java.io.File image = createTempFile(".png", 256);
        ImageResult expected = new ImageResult();
        expected.setCreated(System.currentTimeMillis());
        expected.setData(java.util.Collections.singletonList(new ImageResult.Image("http://localhost/image.png", null)));
        OpenAiService svc = new OpenAiService(api, null);
        when(api.createImageEdit(any(MultipartBody.class))).thenReturn(Single.just(expected));
        ImageResult actual = (ImageResult) svc.createImageEdit(request, image, null);
        assertNotNull((Object) actual, "Should not require executorService for image edit request");
        assertNotNull((Object) actual.getData(), "ImageResult data should not be null");
        assertEquals(1, ((List<ImageResult.Image>)actual.getData()).size(), "Should return 1 image");
    }
}