
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-12-01 using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=createFineTuningJob_652760402b
ROOST_METHOD_SIG_HASH=createFineTuningJob_e5a3db4450

Here are your existing test cases which we found out and are not considered for test generation:

File Path: C:\var\tmp\Roost\RoostGPT\Java-12-01\1768213766\source\openai-java\service\src\test\java\com\theokanning\openai\service\FineTuningTest.java
Tests:
    "@Test
void createFineTuningJob() {
        Hyperparameters hyperparameters = Hyperparameters.builder().nEpochs(4).build();
        FineTuningJobRequest request = FineTuningJobRequest.builder().trainingFile(fileId).model("gpt-3.5-turbo").hyperparameters(hyperparameters).build();
        FineTuningJob fineTuningJob = service.createFineTuningJob(request);
        fineTuningJobId = fineTuningJob.getId();
        assertNotNull(fineTuningJob);
    }
"Scenario 1: Creating a fine-tuning job with a valid request

Details:  
  TestName: createFineTuningJobWithValidRequest
  Description: Verifies that the createFineTuningJob method successfully returns a FineTuningJob for a properly formed FineTuningJobRequest containing valid file ID, model ID, and hyperparameters.

Execution:
  Arrange: Prepare a FineTuningJobRequest object with correct training file ID, an available model identifier, and valid hyperparameters.
  Act: Call createFineTuningJob using the prepared request.
  Assert: Use assertions to check that a non-null FineTuningJob is returned and key fields are properly populated.
Validation: 
  The assertion ensures that, under normal circumstances, the API connection and serialization logic correctly handle a happy path scenario and return a constructed FineTuningJob object to the caller.
  This is crucial to establish that the main business case for fine-tuning job creation works as intended.


Scenario 2: Handling HttpException due to invalid training file

Details:  
  TestName: handleHttpExceptionOnInvalidTrainingFile
  Description: Checks that createFineTuningJob propagates the correct OpenAiHttpException when the underlying API call fails due to an invalid training file reference.

Execution:
  Arrange: Mock the underlying OpenAiApi to throw an HttpException when called with a FineTuningJobRequest referencing an invalid file ID.
  Act: Call createFineTuningJob with the faulty request.
  Assert: Assert that an OpenAiHttpException is thrown and contains the expected error details.
Validation: 
  The validation confirms the error-handling logic in execute(Single) works as intended, properly parsing and transforming HttpExceptions to domain-specific exceptions so that clients can handle API errors appropriately.


Scenario 3: Propagating IOException on error body parsing failure

Details:  
  TestName: propagateIOExceptionWhenErrorBodyCannotBeParsed
  Description: Ensures that if an HttpException occurs and its error body cannot be parsed into an OpenAiError due to IOException, the original HttpException is thrown as per the logic in execute(Single).

Execution:
  Arrange: Mock OpenAiApi to throw HttpException, then simulate errorBody.string() throwing IOException during error parsing.
  Act: Call createFineTuningJob with any FineTuningJobRequest.
  Assert: Assert that the method throws the original HttpException without wrapping it.
Validation: 
  Validates robustness in error-handling code by exposing cases where even error details cannot be parsed, ensuring the stacktrace is preserved for diagnostics.


Scenario 4: Null request parameter handling

Details:  
  TestName: handleNullFineTuningJobRequest
  Description: Checks the behavior when a null FineTuningJobRequest is passed to createFineTuningJob, ensuring proper exception or error-handling.

Execution:
  Arrange: Prepare a null FineTuningJobRequest.
  Act: Call createFineTuningJob with null as the parameter.
  Assert: Assert that the method throws a NullPointerException or handles the case according to implementation.
Validation: 
  It verifies the API’s contract regarding required parameters, ensuring that consumers of the service get clear signals if/when they misuse the method.


Scenario 5: Fine-tuning job request with missing mandatory fields

Details:  
  TestName: createFineTuningJobWithMissingFields
  Description: Tests how createFineTuningJob behaves when a FineTuningJobRequest is missing mandatory fields such as trainingFile or model; expects an error.

Execution:
  Arrange: Create a FineTuningJobRequest with one or more mandatory fields set to null or left unset.
  Act: Pass this request to createFineTuningJob.
  Assert: Assert that an OpenAiHttpException or similar is thrown, with the error indicating which field is missing.
Validation: 
  Ensures strict input validation at the API or service layer, checking that the system responds clearly to incomplete payloads according to OpenAI contract.


Scenario 6: Handling API timeout exception

Details:  
  TestName: handleApiTimeoutException
  Description: Tests the createFineTuningJob method’s response when the underlying API call times out, such as due to network or service unavailability.

Execution:
  Arrange: Configure OpenAiApi mock to simulate a timeout when createFineTuningJob is called.
  Act: Call createFineTuningJob.
  Assert: Assert that a timeout exception is thrown.
Validation: 
  Confirms reliability of error signaling for client-side network issues or service instability, ensuring calling applications can implement retry or fallback logic.


Scenario 7: API returns empty FineTuningJob object

Details:  
  TestName: createFineTuningJobReturnsEmptyObject
  Description: Evaluates how the method handles responses where the API returns a FineTuningJob object that is technically present but has all fields unset or empty.

Execution:
  Arrange: Mock OpenAiApi to return an empty FineTuningJob object (with fields unset or at default).
  Act: Call createFineTuningJob with a valid request.
  Assert: Assert that the returned FineTuningJob is non-null but contains empty/invalid fields.
Validation: 
  Demonstrates how downstream code should react when the API returns minimal information, ensuring fields are checked and not implicitly relied upon.


Scenario 8: Excessive hyperparameters in request

Details:  
  TestName: createFineTuningJobWithExcessiveHyperparameters
  Description: Tests whether createFineTuningJob correctly handles a request where hyperparameters object contains an excessive number of parameters or unsupported settings.

Execution:
  Arrange: Prepare a FineTuningJobRequest with a Hyperparameters object containing extra or invalid fields.
  Act: Call the method with this request.
  Assert: Assert proper error is thrown or unsupported parameters are ignored.
Validation: 
  Confirms if the service strictly enforces supported fields or ignores unknown ones, clarifying payload flexibility for automation and tooling.


Scenario 9: API returns malformed response

Details:  
  TestName: handleMalformedFineTuningJobApiResponse
  Description: Checks system behavior when the API returns a response body that cannot be deserialized into a FineTuningJob due to invalid or unexpected JSON.

Execution:
  Arrange: Mock OpenAiApi to return malformed JSON for the FineTuningJob.
  Act: Call createFineTuningJob.
  Assert: Assert that a deserialization exception is thrown.
Validation: 
  Validates the service’s resilience to backend issues or contract changes and its ability to surface serialization problems without crashing the application.


Scenario 10: Multiple concurrent fine-tuning job creation

Details:  
  TestName: concurrentFineTuningJobCreation
  Description: Tests the behavior of createFineTuningJob when invoked concurrently from multiple threads to ensure proper thread safety and lack of cross-request contamination.

Execution:
  Arrange: Set up multiple FineTuningJobRequest instances with unique parameters and initiate parallel invocations of createFineTuningJob, possibly using an ExecutorService.
  Act: Execute all calls concurrently.
  Assert: Assert each call’s result is independent and correct.
Validation: 
  Ensures the OpenAiService’s internal state and the underlying API client are thread-safe and suitable for use in high-load, multi-threaded environments.


Scenario 11: Service instantiated with custom ExecutorService

Details:
  TestName: createFineTuningJobWithCustomExecutorService
  Description: Validates that createFineTuningJob operates as expected when OpenAiService is instantiated with a custom ExecutorService, especially with respect to resource shutdown and error propagation.

Execution:
  Arrange: Construct OpenAiService with a custom ExecutorService and valid OpenAiApi mock. Prepare a valid FineTuningJobRequest.
  Act: Call createFineTuningJob and observe outcomes.
  Assert: Assert result is handled the same as default instantiation.
Validation:
  Provides confidence that all valid object construction paths of OpenAiService act equivalently during fine-tuning job creation, important for service integration flexibility.


Scenario 12: Large training file scenario

Details:
  TestName: createFineTuningJobWithLargeTrainingFile
  Description: Examines service behavior and performance by simulating a FineTuningJobRequest where the training file size significantly exceeds typical limits, testing memory footprint and latency.

Execution:
  Arrange: Prepare a FineTuningJobRequest referencing a large training file ID.
  Act: Call createFineTuningJob.
  Assert: Assert success or verify that expected resource constraints (such as timeouts or resource errors) are surfaced appropriately.
Validation:
  Verifies that the method’s logic holds for large payloads and that the API or service layer reliably communicates problems related to resource limitations.


Scenario 13: Invalid model identifier in FineTuningJobRequest

Details:
  TestName: createFineTuningJobWithInvalidModelId
  Description: Tests how the createFineTuningJob method handles a FineTuningJobRequest containing a model identifier not recognized by the OpenAI backend.

Execution:
  Arrange: Prepare the request with a model ID that does not exist.
  Act: Call createFineTuningJob.
  Assert: Assert correct error propagation and message.
Validation:
  Ensures that the method returns clear, actionable feedback when underlying resource references in the request are incorrect.


*/

// ********RoostGPT********
package com.theokanning.openai.service;import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.function.Executable;
import org.mockito.Mockito;
import org.mockito.stubbing.Answer;
import io.reactivex.Single;
import retrofit2.HttpException;
import okhttp3.ResponseBody;
import com.theokanning.openai.OpenAiApi;
import com.theokanning.openai.fine_tuning.FineTuningJob;
import com.theokanning.openai.fine_tuning.FineTuningJobRequest;
import com.theokanning.openai.fine_tuning.Hyperparameters;
import com.theokanning.openai.OpenAiError;
import com.theokanning.openai.OpenAiHttpException;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.node.TextNode;
import com.theokanning.openai.*;
import com.theokanning.openai.assistants.*;
import com.theokanning.openai.audio.*;
import com.theokanning.openai.billing.BillingUsage;
import com.theokanning.openai.billing.Subscription;
import com.theokanning.openai.client.OpenAiApi;
import com.theokanning.openai.completion.CompletionChunk;
import com.theokanning.openai.completion.CompletionRequest;
import com.theokanning.openai.completion.CompletionResult;
import com.theokanning.openai.completion.chat.*;
import com.theokanning.openai.edit.EditRequest;
import com.theokanning.openai.edit.EditResult;
import com.theokanning.openai.embedding.EmbeddingRequest;
import com.theokanning.openai.embedding.EmbeddingResult;
import com.theokanning.openai.file.File;
import com.theokanning.openai.fine_tuning.FineTuningEvent;
import com.theokanning.openai.finetune.FineTuneEvent;
import com.theokanning.openai.finetune.FineTuneRequest;
import com.theokanning.openai.finetune.FineTuneResult;
import com.theokanning.openai.image.CreateImageEditRequest;
import com.theokanning.openai.image.CreateImageRequest;
import com.theokanning.openai.image.CreateImageVariationRequest;
import com.theokanning.openai.image.ImageResult;
import com.theokanning.openai.messages.Message;
import com.theokanning.openai.messages.MessageFile;
import com.theokanning.openai.messages.MessageRequest;
import com.theokanning.openai.messages.ModifyMessageRequest;
import com.theokanning.openai.model.Model;
import com.theokanning.openai.moderation.ModerationRequest;
import com.theokanning.openai.moderation.ModerationResult;
import com.theokanning.openai.runs.CreateThreadAndRunRequest;
import com.theokanning.openai.runs.Run;
import com.theokanning.openai.runs.RunCreateRequest;
import com.theokanning.openai.runs.RunStep;
import com.theokanning.openai.runs.SubmitToolOutputsRequest;
import com.theokanning.openai.threads.Thread;
import com.theokanning.openai.threads.ThreadRequest;
import io.reactivex.BackpressureStrategy;
import io.reactivex.Flowable;
import okhttp3.*;
import retrofit2.Call;
import retrofit2.Retrofit;
import retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory;
import retrofit2.converter.jackson.JacksonConverterFactory;
import javax.validation.constraints.NotNull;
import java.time.Duration;
import java.time.LocalDate;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;

class OpenAiServiceCreateFineTuningJobTest {
    @Test
    @Tag("valid")
    void testCreateFineTuningJobWithValidRequest() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("validTrainingFileId"); // set dummy file ID
        request.setModel("valid-model-id");
        Hyperparameters hyperparams = new Hyperparameters();
        // Note: Removed setLearningRate, as this method does not exist per errors above. If needed, set via a map.
        Map<String, Object> hpMap = new HashMap<>();
        hpMap.put("learning_rate", 0.01);
        hyperparams.setAdditionalProperties(hpMap);
        request.setHyperparameters(hyperparams);
        FineTuningJob expectedJob = new FineTuningJob();
        expectedJob.setId("ft_job_123");
        expectedJob.setTrainingFile("validTrainingFileId");
        expectedJob.setModel("valid-model-id");
        expectedJob.setHyperparameters(hyperparams);
        Mockito.when(api.createFineTuningJob(request))
                .thenReturn(Single.just(expectedJob));
        OpenAiService service = new OpenAiService(api);
        FineTuningJob actualJob = (FineTuningJob)service.createFineTuningJob(request);
        Assertions.assertNotNull(actualJob);
        Assertions.assertEquals(expectedJob.getId(), actualJob.getId());
        Assertions.assertEquals(expectedJob.getTrainingFile(), actualJob.getTrainingFile());
        Assertions.assertEquals(expectedJob.getModel(), actualJob.getModel());
        // Compare map for learning rate
        Assertions.assertEquals(
                expectedJob.getHyperparameters().getAdditionalProperties().get("learning_rate"),
                actualJob.getHyperparameters().getAdditionalProperties().get("learning_rate")
        );
    }
    @Test
    @Tag("invalid")
    void testHandleHttpExceptionOnInvalidTrainingFile() throws IOException {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("invalidTrainingFileId"); // deliberately invalid value
        request.setModel("valid-model-id");
        HttpException httpException = Mockito.mock(HttpException.class);
        ResponseBody errorBody = Mockito.mock(ResponseBody.class);
        String errorJson = "{\"error\":{\"message\":\"Invalid training file.\",\"type\":\"invalid_request_error\"}}";
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.error(httpException));
        retrofit2.Response<?> mockResponse = Mockito.mock(retrofit2.Response.class);
        Mockito.when(httpException.response()).thenReturn((retrofit2.Response) mockResponse);
        Mockito.when(mockResponse.errorBody()).thenReturn(errorBody);
        Mockito.when(errorBody.string()).thenReturn(errorJson);
        Mockito.when(httpException.code()).thenReturn(400);
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(request);
        OpenAiHttpException ex = (OpenAiHttpException)Assertions.assertThrows(OpenAiHttpException.class, act);
        Assertions.assertNotNull(ex);
        Assertions.assertEquals(400, ex.getHttpStatus());
        Assertions.assertTrue(ex.getMessage().contains("Invalid training file."));
    }
    @Test
    @Tag("invalid")
    void testPropagateIOExceptionWhenErrorBodyCannotBeParsed() throws IOException {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("invalidTrainingFileId");
        request.setModel("valid-model-id");
        HttpException httpException = Mockito.mock(HttpException.class);
        ResponseBody errorBody = Mockito.mock(ResponseBody.class);
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.error(httpException));
        retrofit2.Response<?> mockResponse = Mockito.mock(retrofit2.Response.class);
        Mockito.when(httpException.response()).thenReturn((retrofit2.Response) mockResponse);
        Mockito.when(mockResponse.errorBody()).thenReturn(errorBody);
        Mockito.when(errorBody.string()).thenThrow(new IOException("Parsing failed"));
        Mockito.when(httpException.code()).thenReturn(500);
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(request);
        HttpException ex = (HttpException)Assertions.assertThrows(HttpException.class, act);
        Assertions.assertNotNull(ex);
        Assertions.assertEquals(500, ex.code());
    }
    @Test
    @Tag("invalid")
    void testHandleNullFineTuningJobRequest() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(null);
        Assertions.assertThrows(NullPointerException.class, act);
    }
    @Test
    @Tag("invalid")
    void testCreateFineTuningJobWithMissingFields() throws IOException {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest(); // missing mandatory fields
        String errorJson = "{\"error\":{\"message\":\"Missing required parameters: training_file, model\",\"type\":\"invalid_request_error\"}}";
        HttpException httpException = Mockito.mock(HttpException.class);
        ResponseBody errorBody = Mockito.mock(ResponseBody.class);
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.error(httpException));
        retrofit2.Response<?> mockResponse = Mockito.mock(retrofit2.Response.class);
        Mockito.when(httpException.response()).thenReturn((retrofit2.Response) mockResponse);
        Mockito.when(mockResponse.errorBody()).thenReturn(errorBody);
        Mockito.when(errorBody.string()).thenReturn(errorJson);
        Mockito.when(httpException.code()).thenReturn(400);
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(request);
        OpenAiHttpException ex = (OpenAiHttpException)Assertions.assertThrows(OpenAiHttpException.class, act);
        Assertions.assertTrue(ex.getMessage().contains("Missing required parameters"));
    }
    @Test
    @Tag("boundary")
    void testHandleApiTimeoutException() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("some-file-id");
        request.setModel("some-model-id");
        Mockito.when(api.createFineTuningJob(request))
                .thenAnswer((Answer<Single<FineTuningJob>>) invocation -> {
                    return Single.<FineTuningJob>create(emitter -> {
                        try {
                            TimeUnit.MILLISECONDS.sleep(20); // simulate a delay
                            emitter.onError(new TimeoutException("API call timed out"));
                        } catch (InterruptedException e) {
                            emitter.onError(e);
                        }
                    });
                });
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(request);
        Throwable ex = Assertions.assertThrows(Throwable.class, act);
        Assertions.assertTrue(ex instanceof TimeoutException);
        Assertions.assertTrue(((TimeoutException) ex).getMessage().contains("API call timed out"));
    }
    @Test
    @Tag("boundary")
    void testCreateFineTuningJobReturnsEmptyObject() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("validTrainingFileId");
        request.setModel("valid-model-id");
        FineTuningJob emptyJob = new FineTuningJob();
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.just(emptyJob));
        OpenAiService service = new OpenAiService(api);
        FineTuningJob actualJob = (FineTuningJob)service.createFineTuningJob(request);
        Assertions.assertNotNull(actualJob);
        Assertions.assertNull(actualJob.getId());
        Assertions.assertNull(actualJob.getTrainingFile());
        Assertions.assertNull(actualJob.getModel());
        Assertions.assertNull(actualJob.getHyperparameters());
    }
    @Test
    @Tag("boundary")
    void testCreateFineTuningJobWithExcessiveHyperparameters() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("validTrainingFileId");
        request.setModel("valid-model-id");
        Hyperparameters hyperparams = new Hyperparameters();
        Map<String, Object> customHyperparams = new HashMap<>();
        customHyperparams.put("learning_rate", 0.01);
        customHyperparams.put("momentum", 0.99); // excessive value for test
        customHyperparams.put("extra_param", 12345); // unsupported value for test
        hyperparams.setAdditionalProperties(customHyperparams);
        request.setHyperparameters(hyperparams);
        String errorJson = "{\"error\":{\"message\":\"Unsupported hyperparameter: extra_param\",\"type\":\"invalid_request_error\"}}";
        HttpException httpException = Mockito.mock(HttpException.class);
        ResponseBody errorBody = Mockito.mock(ResponseBody.class);
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.error(httpException));
        retrofit2.Response<?> mockResponse = Mockito.mock(retrofit2.Response.class);
        Mockito.when(httpException.response()).thenReturn((retrofit2.Response) mockResponse);
        Mockito.when(mockResponse.errorBody()).thenReturn(errorBody);
        Mockito.when(errorBody.string()).thenReturn(errorJson);
        Mockito.when(httpException.code()).thenReturn(400);
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(request);
        OpenAiHttpException ex = (OpenAiHttpException)Assertions.assertThrows(OpenAiHttpException.class, act);
        Assertions.assertTrue(ex.getMessage().contains("Unsupported hyperparameter"));
    }
    @Test
    @Tag("boundary")
    void testHandleMalformedFineTuningJobApiResponse() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("validTrainingFileId");
        request.setModel("valid-model-id");
        Mockito.when(api.createFineTuningJob(request))
                .thenReturn(Single.error(new JsonParseException(null, "Malformed JSON")));
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(request);
        JsonParseException ex = (JsonParseException)Assertions.assertThrows(JsonParseException.class, act);
        Assertions.assertTrue(ex.getMessage().contains("Malformed JSON"));
    }
    @Test
    @Tag("integration")
    void testConcurrentFineTuningJobCreation() throws InterruptedException, ExecutionException {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        ExecutorService executor = Executors.newFixedThreadPool(2);
        FineTuningJobRequest request1 = new FineTuningJobRequest();
        request1.setTrainingFile("trainingFile1");
        request1.setModel("modelA");
        FineTuningJobRequest request2 = new FineTuningJobRequest();
        request2.setTrainingFile("trainingFile2");
        request2.setModel("modelB");
        FineTuningJob job1 = new FineTuningJob();
        job1.setId("concurrent-job-1");
        job1.setTrainingFile("trainingFile1");
        job1.setModel("modelA");
        FineTuningJob job2 = new FineTuningJob();
        job2.setId("concurrent-job-2");
        job2.setTrainingFile("trainingFile2");
        job2.setModel("modelB");
        Mockito.when(api.createFineTuningJob(request1)).thenReturn(Single.just(job1));
        Mockito.when(api.createFineTuningJob(request2)).thenReturn(Single.just(job2));
        OpenAiService service = new OpenAiService(api, executor);
        Callable<FineTuningJob> task1 = () -> (FineTuningJob)service.createFineTuningJob(request1);
        Callable<FineTuningJob> task2 = () -> (FineTuningJob)service.createFineTuningJob(request2);
        Future<FineTuningJob> future1 = executor.submit(task1);
        Future<FineTuningJob> future2 = executor.submit(task2);
        FineTuningJob actualJob1 = (FineTuningJob)future1.get();
        FineTuningJob actualJob2 = (FineTuningJob)future2.get();
        Assertions.assertNotNull(actualJob1);
        Assertions.assertNotNull(actualJob2);
        Assertions.assertEquals(job1.getId(), actualJob1.getId());
        Assertions.assertEquals(job2.getId(), actualJob2.getId());
        Assertions.assertEquals("trainingFile1", actualJob1.getTrainingFile());
        Assertions.assertEquals("trainingFile2", actualJob2.getTrainingFile());
        executor.shutdown();
    }
    @Test
    @Tag("integration")
    void testCreateFineTuningJobWithCustomExecutorService() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        ExecutorService customExecutor = Executors.newSingleThreadExecutor();
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("validTrainingFileId");
        request.setModel("valid-model-id");
        FineTuningJob expectedJob = new FineTuningJob();
        expectedJob.setId("custom-executor-job");
        expectedJob.setTrainingFile("validTrainingFileId");
        expectedJob.setModel("valid-model-id");
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.just(expectedJob));
        OpenAiService service = new OpenAiService(api, customExecutor);
        FineTuningJob actualJob = (FineTuningJob)service.createFineTuningJob(request);
        Assertions.assertNotNull(actualJob);
        Assertions.assertEquals(expectedJob.getId(), actualJob.getId());
        Assertions.assertEquals(expectedJob.getTrainingFile(), actualJob.getTrainingFile());
        customExecutor.shutdown();
    }
    @Test
    @Tag("boundary")
    void testCreateFineTuningJobWithLargeTrainingFile() {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("very-large-training-file-id"); // large file reference
        request.setModel("valid-model-id");
        FineTuningJob expectedJob = new FineTuningJob();
        expectedJob.setId("large-file-job");
        expectedJob.setTrainingFile("very-large-training-file-id");
        expectedJob.setModel("valid-model-id");
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.just(expectedJob));
        OpenAiService service = new OpenAiService(api);
        FineTuningJob actualJob = (FineTuningJob)service.createFineTuningJob(request);
        Assertions.assertNotNull(actualJob);
        Assertions.assertEquals("very-large-training-file-id", actualJob.getTrainingFile());
        // To simulate timeout/error, setup the mock to return Single.error but business logic currently handles Single.just.
    }
    @Test
    @Tag("invalid")
    void testCreateFineTuningJobWithInvalidModelId() throws IOException {
        com.theokanning.openai.OpenAiApi api = Mockito.mock(com.theokanning.openai.OpenAiApi.class);
        FineTuningJobRequest request = new FineTuningJobRequest();
        request.setTrainingFile("validTrainingFileId");
        request.setModel("invalid-model-id"); // Intentionally invalid
        String errorJson = "{\"error\":{\"message\":\"Model identifier 'invalid-model-id' not found.\",\"type\":\"invalid_request_error\"}}";
        HttpException httpException = Mockito.mock(HttpException.class);
        ResponseBody errorBody = Mockito.mock(ResponseBody.class);
        Mockito.when(api.createFineTuningJob(request)).thenReturn(Single.error(httpException));
        retrofit2.Response<?> mockResponse = Mockito.mock(retrofit2.Response.class);
        Mockito.when(httpException.response()).thenReturn((retrofit2.Response) mockResponse);
        Mockito.when(mockResponse.errorBody()).thenReturn(errorBody);
        Mockito.when(errorBody.string()).thenReturn(errorJson);
        Mockito.when(httpException.code()).thenReturn(400);
        OpenAiService service = new OpenAiService(api);
        Executable act = () -> service.createFineTuningJob(request);
        OpenAiHttpException ex = (OpenAiHttpException)Assertions.assertThrows(OpenAiHttpException.class, act);
        Assertions.assertTrue(ex.getMessage().contains("not found"));
    }
}