

// ********RoostGPT********
/*
Test generated by RoostGPT for test zbio-jan-7 using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=encode_3f6c1a6ca9
ROOST_METHOD_SIG_HASH=encode_0d52df1219

Scenario 1: Encode with a null text input

Details:  
  TestName: encodeWithNullText
  Description: This test checks the behavior of the encode method when the text argument provided is null. The scenario verifies that when the input text is null, the method correctly determines that text is "blank" and returns an empty list of integers.
Execution:
  Arrange: Prepare a valid model name present in the modelMap, and set the text input as null.
  Act: Invoke encode(modelName, null).
  Assert: Use assertions to ensure that the returned list is empty.
Validation: 
  The assertion verifies that the method identifies null text as blank and does not attempt tokenization, returning an empty list. It is significant for preventing null pointer issues and ensuring graceful handling of missing data.


Scenario 2: Encode with a text containing only whitespace

Details:  
  TestName: encodeWithWhitespaceOnlyText
  Description: This scenario ensures that if the text consists solely of whitespace characters, the encode method detects the text input as blank and returns an empty list without passing it to the Encoding instance.
Execution:
  Arrange: Select a valid model name from modelMap. Set the text to a string containing only spaces, tabs, or other recognized blank characters.
  Act: Call encode(modelName, "    \t\n").
  Assert: Confirm that the returned list is empty.
Validation: 
  Validation confirms that the method's handling of “blank” logic is robust, preventing unnecessary processing of text with no content, which is vital for efficiency and correctness.


Scenario 3: Encode with valid model name and normal text input

Details:  
  TestName: encodeWithValidModelAndNormalText
  Description: This test evaluates the normal functionality of the encode method using a valid model name mapped in modelMap and a typical, non-blank text string. It expects the text to be encoded correctly into a non-empty integer list.
Execution:
  Arrange: Choose a model name known to modelMap, and set the text to a meaningful string (e.g., "Hello world").
  Act: Invoke encode(modelName, "Hello world").
  Assert: Verify that the returned list contains the expected encoded integer values and is not empty.
Validation: 
  This confirms the main business logic where encoding is executed successfully for correct inputs, ensuring core functionality.


Scenario 4: Encode with model name not present in modelMap

Details:  
  TestName: encodeWithInvalidModelName
  Description: Tests the behavior when encode is called with a modelName that does not exist in the modelMap, evaluating whether the method returns an empty list as specified in its error handling logic.
Execution:
  Arrange: Prepare a non-existent model name (e.g., "unknown-model") and a valid text.
  Act: Call encode("unknown-model", "Some text").
  Assert: Assert that the result is an empty list.
Validation: 
  This validation assures the robustness of error handling for unknown or unsupported models, preventing runtime errors or null pointer exceptions.


Scenario 5: Encode with empty string as text input

Details:  
  TestName: encodeWithEmptyText
  Description: Verifies that encode returns an empty list when provided with an empty string, as an empty string should be considered "blank".
Execution:
  Arrange: Select a valid model name, and set text to "" (empty string).
  Act: Invoke encode(modelName, "").
  Assert: Ensure the returned list is empty.
Validation: 
  The test verifies the strict definition of blank inputs and validates that no tokens are returned for empty strings, keeping results consistent with design.


Scenario 6: Encode with special blank Unicode characters

Details:  
  TestName: encodeWithSpecialBlankUnicodeText
  Description: In this scenario, the test checks if the encode method handles text composed only of characters defined as blank by isBlankChar, such as 65279, 8234, etc.
Execution:
  Arrange: Use a valid model name, and set text to a string of Unicode characters considered blank (e.g., "\u65279\u8234").
  Act: Call encode(modelName, textWithBlankUnicodeChars).
  Assert: Assert that the returned list is empty.
Validation: 
  This ensures the isBlank logic correctly recognizes all defined blank characters beyond just space and tab, providing comprehensive input validation.


Scenario 7: Encode with non-string text (simulate edge case with CharSequence subtype)

Details:  
  TestName: encodeWithCharSequenceSubtypeInput
  Description: Checks behavior when text is provided as a CharSequence implementation other than String (e.g., StringBuilder), testing compatibility of isBlank and encoding logic.
Execution:
  Arrange: Select a valid model name and instantiate a CharSequence implementation with non-blank data, such as a StringBuilder containing "Tokenize this".
  Act: Call encode(modelName, textFromStringBuilder.toString()).
  Assert: Verify output matches expected encoding as with normal text.
Validation: 
  Validates that the encode method functions consistently with any CharSequence (converted to String), confirming method versatility.


Scenario 8: Encode with a valid model and very large text input

Details:  
  TestName: encodeWithLargeText
  Description: Evaluates performance and correctness when encode is used with a valid model name and an extremely large text, such as a long paragraph or file contents.
Execution:
  Arrange: Choose a valid model and prepare a lengthy text string.
  Act: Invoke encode(modelName, largeText).
  Assert: Ensure returned list is not empty, and its size corresponds to the number of tokens expected.
Validation: 
  This test is significant for validating scalability and ensuring that the method does not fail or behave inconsistently with large inputs.


Scenario 9: Encode with null model name

Details:  
  TestName: encodeWithNullModelName
  Description: Checks handling when the modelName passed is null. It verifies that, since getEncoding(null) will return null (as the modelMap will not contain a null key), encode should return an empty list instead of attempting to encode with a null Encoding.
Execution:
  Arrange: Set modelName as null and provide a valid, non-blank text.
  Act: Call encode(null, "Valid text").
  Assert: Confirm the result is an empty list.
Validation: 
  This tests input validation for model name and ensures the method safely handles nulls, reinforcing reliability.


Scenario 10: Encode with valid model but Encoding returns null (simulate unexpected registry behavior)

Details:  
  TestName: encodeWithNullEncodingFromRegistry
  Description: Simulates the situation where getEncoding(modelName) improperly returns null due to registry misconfiguration or unsupported model mapping. Checks if encode then correctly returns an empty list.
Execution:
  Arrange: Use a modelName intentionally mapped to null in modelMap (via test setup or mock).
  Act: Call encode(modelNameMappedToNull, "Some text").
  Assert: Assert that the result is an empty list.
Validation: 
  This covers unexpected internal errors, confirming defensive programming practices and error resilience.


Scenario 11: Encode with valid model and text containing special symbols and emojis

Details:  
  TestName: encodeWithSpecialSymbolText
  Description: Tests encoding of a string with special characters, symbols, and emojis using a valid model. Checks if such content is tokenized correctly.
Execution:
  Arrange: Pick a valid model name and set text to "Hello 😊🚀!".
  Act: Invoke encode(modelName, "Hello 😊🚀!").
  Assert: Verify encoded output matches expected token count.
Validation: 
  Ensures the method supports full Unicode content and does not fail or misinterpret symbols and emojis.


Scenario 12: Encode with model name containing upper/lowercase mismatch

Details:  
  TestName: encodeWithCaseMismatchModelName
  Description: Checks behavior when modelName casing does not match exactly as expected (e.g., "GPT-3.5-TURBO" vs "gpt-3.5-turbo"). Verifies whether encode is case-sensitive and returns appropriate result.
Execution:
  Arrange: Use modelName with different casing than present in modelMap and provide valid text.
  Act: Call encode("GPT-3.5-TURBO", "Text").
  Assert: Assert that the returned list is empty.
Validation: 
  Highlights method sensitivity to input case, indicating whether model names should be normalized or documented as case-sensitive.


Scenario 13: Encode with valid model and empty list returned by Encoding.encode

Details:  
  TestName: encodeWithModelEncodingReturnsEmpty
  Description: Tests that if Encoding.encode returns an empty list (simulating a case where Encoding fails or text contains no recognizable tokens), the outer encode method propagates the empty result correctly.
Execution:
  Arrange: Mock Encoding.encode to return an empty list for some valid input, and insert into modelMap.
  Act: Call encode(modelName, "Unrecognizable input").
  Assert: Check that the result is an empty list.
Validation: 
  Ensures transparency in returning results from underlying encoding and does not obscure or mishandle valid “empty” results.


Scenario 14: Encode with model name mapped to a custom Encoding implementation

Details:  
  TestName: encodeWithCustomEncodingImplementation
  Description: Validates that the method functions with any compatible Encoding implementation in modelMap, not just standard registry-provided ones.
Execution:
  Arrange: Insert a custom Encoding instance implementing the encode method into modelMap under a unique model name. Provide normal text.
  Act: Call encode(customModelName, "Sample input").
  Assert: Check that output matches logic implemented in custom Encoding.
Validation: 
  Provides extensibility confirmation, showing the method supports polymorphic Encoding usage.


Scenario 15: Encode with model name mapped to Encoding with failing encode method (simulate exception)

Details:  
  TestName: encodeWithEncodingThatThrowsException
  Description: This test covers the edge scenario where Encoding.encode throws an exception (e.g., runtime error during encoding), ensuring encode does not propagate the exception or handles it as designed.
Execution:
  Arrange: Insert into modelMap an Encoding mock that throws an exception on encode. Provide valid text.
  Act: Call encode(modelName, "Error-prone input").
  Assert: Check that the test appropriately handles any thrown exceptions or verifies the error handling design.
Validation: 
  This error scenario confirms method stability against unexpected failures in encoding logic, strengthening reliability expectations.


Scenario 16: Encode with model name mapped to Encoding with stateful behavior

Details:  
  TestName: encodeWithStatefulEncoding
  Description: Tests method behavior with an Encoding instance whose encode method's result depends on internal state, ensuring encode propagates results as returned for the provided text.
Execution:
  Arrange: Insert a stateful Encoding instance into modelMap. Call encode with different texts under the same model name.
  Act: Call encode(modelName, text1) and encode(modelName, text2).
  Assert: Verify results differ according to Encoding's state.
Validation: 
  This ensures encode is agnostic to Encoding implementation details and passes through results transparently.


Scenario 17: Encode with valid model and null text, expecting empty output

Details:  
  TestName: encodeWithModelAndNullTextReturnsEmpty
  Description: Confirms that for any valid model name, passing null as the text correctly returns an empty list, regardless of Encoding behavior.
Execution:
  Arrange: Select a model name known in modelMap and set text to null.
  Act: Call encode(modelName, null).
  Assert: Assert that the output is an empty list.
Validation: 
  Validates universal null text handling across all models, preventing unnecessary computations.


Scenario 18: Encode with model name mapped to Encoding that returns null (violating contract)

Details:  
  TestName: encodeWithEncodingReturnsNull
  Description: Simulates a scenario where Encoding.encode returns null instead of a List (for faulty implementations), verifying how encode handles such a contract violation.
Execution:
  Arrange: Mock or insert an Encoding in modelMap whose encode(text) returns null.
  Act: Call encode(modelName, "Unexpected Null Case").
  Assert: Assert the method's reaction—is it propagated, wrapped, or handled?
Validation: 
  Tests error handling for downstream defects, ensuring method does not crash on invalid Encoding implementations.


Scenario 19: Encode with excessively long text input that can challenge stack/memory

Details:  
  TestName: encodeWithExcessivelyLongTextHandling
  Description: Checks if encode gracefully processes or rejects extremely large text input that may risk memory or stack overflows, ensuring system stability for edge cases.
Execution:
  Arrange: Select a valid model name and prepare a multi-megabyte string input.
  Act: Call encode(modelName, longTextInput).
  Assert: Check that output is either a large list or method throws controlled exceptions, as specified by design.
Validation: 
  Highlights potential scalability problems or reveals bounding logic needed for safe operation with huge inputs.


Scenario 20: Encode with valid model and text containing only non-blank Unicode characters

Details:  
  TestName: encodeWithNonBlankUnicodeText
  Description: Ensures that text comprised of various non-blank Unicode characters (e.g., multilingual or CJK script) is encoded properly.
Execution:
  Arrange: Use a valid model name and text containing multilingual characters (e.g., "你好，世界").
  Act: Call encode(modelName, "你好，世界").
  Assert: Validate the output list matches encoding results for non-blank Unicode.
Validation: 
  Assures complete language coverage and multicultural compatibility of the encode method.

*/

// ********RoostGPT********
package com.theokanning.openai.utils;import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import com.knuddels.jtokkit.api.Encoding;
import com.knuddels.jtokkit.Encodings;
import com.knuddels.jtokkit.api.EncodingRegistry;
import com.knuddels.jtokkit.api.EncodingType;
import com.knuddels.jtokkit.api.ModelType;
import com.theokanning.openai.completion.chat.ChatMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;
import java.lang.reflect.Field;

class TikTokensUtilEncode282Test {
    private static final String VALID_MODEL = "gpt-3.5-turbo-0301";
    private static final String CUSTOM_MODEL = "custom-model";
    private static final String NULL_ENCODING_MODEL = "null-encoding-model";
    private static final String STATEFUL_MODEL = "stateful-model";
    private static final String RETURN_NULL_MODEL = "returnNull-model";
    private static final String THROW_EXCEPTION_MODEL = "throwException-model";
    private static final String EMPTY_ENCODING_MODEL = "emptyEncoding-model";
    private static final String LARGE_TEXT_MODEL = "largeModel";
    private static final String NON_BLANK_UNICODE_MODEL = "unicode-model";
    private Encoding dummyEncoding;
    private Encoding emptyEncoding;
    private Encoding nullReturnEncoding;
    private Encoding throwExceptionEncoding;
    private Encoding customEncoding;
    private Encoding statefulEncoding;
    private Encoding nonBlankUnicodeEncoding;
    private final Map<Integer, List<Integer>> statefulResults = new HashMap<>();
    private Map<String, Encoding> backingModelMap;
    @BeforeEach
    void setup() throws Exception {
        dummyEncoding = new Encoding() {
            @Override
            public List<Integer> encode(String text) {
                if (text == null) return Collections.emptyList();
                // only return empty for blank text (as per isBlank logic from TikTokensUtil)
                if (TikTokensUtil.isBlank(text)) return Collections.emptyList();
                List<Integer> out = new ArrayList<>();
                for (char c : text.toCharArray())
                    out.add((int) c);
                return out;
            }
            @Override
            public String decode(List<Integer> encoded) {
                StringBuilder sb = new StringBuilder();
                for (Integer i : encoded) sb.append((char)(int)i);
                return sb.toString();
            }
            @Override
            public String getName() { return "dummy"; }
        };
        emptyEncoding = new Encoding() {
            @Override
            public List<Integer> encode(String text) {
                return Collections.emptyList();
            }
            @Override
            public String decode(List<Integer> encoded) {
                return "";
            }
            @Override
            public String getName() { return "empty"; }
        };
        nullReturnEncoding = new Encoding() {
            @Override
            public List<Integer> encode(String text) {
                return null;
            }
            @Override
            public String decode(List<Integer> encoded) {
                return null;
            }
            @Override
            public String getName() { return "nullReturn"; }
        };
        throwExceptionEncoding = new Encoding() {
            @Override
            public List<Integer> encode(String text) {
                throw new RuntimeException("Test exception for encode");
            }
            @Override
            public String decode(List<Integer> encoded) {
                return null;
            }
            @Override
            public String getName() { return "throwException"; }
        };
        customEncoding = new Encoding() {
            @Override
            public List<Integer> encode(String text) {
                if (text == null) return Collections.emptyList();
                // only return empty for blank text (as per isBlank logic from TikTokensUtil)
                if (TikTokensUtil.isBlank(text)) return Collections.emptyList();
                List<Integer> list = new ArrayList<>();
                for (int i = 0; i < text.length(); i++) list.add(i); // Custom logic: index values
                return list;
            }
            @Override
            public String decode(List<Integer> encoded) {
                return null;
            }
            @Override
            public String getName() { return "custom"; }
        };
        statefulEncoding = new Encoding() {
            private int state = 0;
            @Override
            public List<Integer> encode(String text) {
                state++;
                List<Integer> result = new ArrayList<>();
                result.add(state); // state increments with every call
                statefulResults.put(state, result);
                return result;
            }
            @Override
            public String decode(List<Integer> encoded) {
                return null;
            }
            @Override
            public String getName() { return "stateful"; }
        };
        nonBlankUnicodeEncoding = new Encoding() {
            @Override
            public List<Integer> encode(String text) {
                if (text == null || TikTokensUtil.isBlank(text)) return Collections.emptyList();
                List<Integer> out = new ArrayList<>();
                for (char c : text.toCharArray())
                    out.add((int)c);
                return out;
            }
            @Override
            public String decode(List<Integer> encoded) {
                StringBuilder sb = new StringBuilder();
                for (Integer i : encoded) sb.append((char)(int)i);
                return sb.toString();
            }
            @Override
            public String getName() { return "nonBlankUnicode"; }
        };
        // Put encodings into TikTokensUtil.modelMap reflectively (because it's private static final)
        Field modelMapField = TikTokensUtil.class.getDeclaredField("modelMap");
        modelMapField.setAccessible(true);
        @SuppressWarnings("unchecked")
        Map<String, Encoding> modelMap = (Map<String, Encoding>) modelMapField.get(null);
        modelMap.put(VALID_MODEL, dummyEncoding);
        modelMap.put(CUSTOM_MODEL, customEncoding);
        modelMap.put(NULL_ENCODING_MODEL, null); // for registry returns null
        modelMap.put(STATEFUL_MODEL, statefulEncoding);
        modelMap.put(RETURN_NULL_MODEL, nullReturnEncoding);
        modelMap.put(THROW_EXCEPTION_MODEL, throwExceptionEncoding);
        modelMap.put(EMPTY_ENCODING_MODEL, emptyEncoding);
        modelMap.put(LARGE_TEXT_MODEL, dummyEncoding);
        modelMap.put(NON_BLANK_UNICODE_MODEL, nonBlankUnicodeEncoding);
        this.backingModelMap = modelMap;
    }
    @AfterEach
    void teardown() {
        if (backingModelMap != null) {
            backingModelMap.clear();
        }
        statefulResults.clear();
    }
    @Test
    @Tag("valid")
    public void testEncodeWithNullText() {
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, null);
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("valid")
    public void testEncodeWithWhitespaceOnlyText() {
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, "   \t\n");
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("valid")
    public void testEncodeWithValidModelAndNormalText() {
        String text = "Hello world";
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, text);
        assertFalse(((List<Integer>)result).isEmpty());
        assertEquals((int)text.charAt(0), (int)((List<Integer>) result).get(0));
        assertEquals((int)text.charAt(text.length()-1), (int)((List<Integer>) result).get(result.size()-1));
        assertEquals(text.length(), ((List<Integer>) result).size());
    }
    @Test
    @Tag("invalid")
    public void testEncodeWithInvalidModelName() {
        List<Integer> result = TikTokensUtil.encode("unknown-model", "Some text");
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("valid")
    public void testEncodeWithEmptyText() {
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, "");
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("boundary")
    public void testEncodeWithSpecialBlankUnicodeText() {
        String blankUnicode = "\u65279\u8234";
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, blankUnicode);
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("valid")
    public void testEncodeWithCharSequenceSubtypeInput() {
        StringBuilder sb = new StringBuilder("Tokenize this");
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, sb.toString());
        assertEquals(sb.length(), ((List<Integer>) result).size());
        assertEquals((int)sb.charAt(0), (int)((List<Integer>) result).get(0));
        assertEquals((int)sb.charAt(sb.length()-1), (int)((List<Integer>) result).get(sb.length()-1));
    }
    @Test
    @Tag("boundary")
    public void testEncodeWithLargeText() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 5000; i++) {
            sb.append('a');
        }
        List<Integer> result = TikTokensUtil.encode(LARGE_TEXT_MODEL, sb.toString());
        assertFalse(((List<Integer>)result).isEmpty());
        assertEquals(sb.length(), ((List<Integer>) result).size());
    }
    @Test
    @Tag("invalid")
    public void testEncodeWithNullModelName() {
        List<Integer> result = TikTokensUtil.encode((String)null, "Valid text");
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("invalid")
    public void testEncodeWithNullEncodingFromRegistry() {
        List<Integer> result = TikTokensUtil.encode(NULL_ENCODING_MODEL, "Some text");
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("valid")
    public void testEncodeWithSpecialSymbolText() {
        String input = "Hello 😊🚀!";
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, input);
        assertFalse(((List<Integer>)result).isEmpty());
        assertEquals(input.length(), ((List<Integer>) result).size());
        assertEquals((int)'😊', (int)((List<Integer>) result).get(6));
        assertEquals((int)'🚀', (int)((List<Integer>) result).get(7));
    }
    @Test
    @Tag("invalid")
    public void testEncodeWithCaseMismatchModelName() {
        List<Integer> result = TikTokensUtil.encode("GPT-3.5-TURBO", "Text");
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("valid")
    public void testEncodeWithModelEncodingReturnsEmpty() {
        List<Integer> result = TikTokensUtil.encode(EMPTY_ENCODING_MODEL, "Unrecognizable input");
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("integration")
    public void testEncodeWithCustomEncodingImplementation() {
        List<Integer> result = TikTokensUtil.encode(CUSTOM_MODEL, "Sample input");
        assertEquals("Sample input".length(), ((List<Integer>) result).size());
        assertEquals(0, (int)((List<Integer>) result).get(0));
        assertEquals("Sample input".length() - 1, (int)((List<Integer>) result).get(result.size()-1));
    }
    @Test
    @Tag("invalid")
    public void testEncodeWithEncodingThatThrowsException() {
        assertThrows(RuntimeException.class, () ->
            TikTokensUtil.encode(THROW_EXCEPTION_MODEL, "Error-prone input")
        );
    }
    @Test
    @Tag("integration")
    public void testEncodeWithStatefulEncoding() {
        List<Integer> result1 = TikTokensUtil.encode(STATEFUL_MODEL, "A");
        List<Integer> result2 = TikTokensUtil.encode(STATEFUL_MODEL, "B");
        assertNotEquals(result1, result2);
        assertEquals(statefulResults.get(((List<Integer>)result1).get(0)), result1);
        assertEquals(statefulResults.get(((List<Integer>)result2).get(0)), result2);
    }
    @Test
    @Tag("valid")
    public void testEncodeWithModelAndNullTextReturnsEmpty() {
        List<Integer> result = TikTokensUtil.encode(VALID_MODEL, null);
        assertTrue(((List<Integer>)result).isEmpty());
    }
    @Test
    @Tag("invalid")
    public void testEncodeWithEncodingReturnsNull() {
        // This will fail because business logic in TikTokensUtil.encode does not handle null return from encode()
        // Suggestion: TikTokensUtil.encode should check if (encoded == null) and return Collections.emptyList() or handle as needed
        List<Integer> result = TikTokensUtil.encode(RETURN_NULL_MODEL, "Unexpected Null Case");
        assertNull(result); // Based on business logic, this should be handled, else TikTokensUtil logic needs improvement
    }
    @Test
    @Tag("boundary")
    public void testEncodeWithExcessivelyLongTextHandling() {
        StringBuilder sb = new StringBuilder();
        int size = 100000; // TODO: Adjust size as per system capability for edge boundary
        for (int i = 0; i < size; i++) {
            sb.append('x');
        }
        try {
            List<Integer> result = TikTokensUtil.encode(LARGE_TEXT_MODEL, sb.toString());
            assertEquals(size, ((List<Integer>) result).size());
            assertEquals((int)'x', (int)((List<Integer>) result).get(0));
        } catch (Throwable e) {
            fail("Should not throw exception for very large input: " + e);
        }
    }
    @Test
    @Tag("valid")
    public void testEncodeWithNonBlankUnicodeText() {
        String input = "你好，世界";
        List<Integer> result = TikTokensUtil.encode(NON_BLANK_UNICODE_MODEL, input);
        assertFalse(((List<Integer>)result).isEmpty());
        assertEquals(input.length(), ((List<Integer>) result).size());
        assertTrue(((List<Integer>) result).contains((int)'你'));
        assertTrue(((List<Integer>) result).contains((int)'好'));
        assertTrue(((List<Integer>) result).contains((int)'世'));
        assertTrue(((List<Integer>) result).contains((int)'界'));
    }
}